---
version: 2
updates:
  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Asia/Riyadh"
    assignees:
      - "Yokozuna59"
    labels:
      - "maven"
      - "dependencies"
      - "automation"
    reviewers:
      - "Yokozuna59"
    target-branch: "master"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Asia/Riyadh"
    assignees:
      - "Yokozuna59"
    labels:
      - "github-actions"
      - "dependencies"
      - "automation"
    reviewers:
      - "Yokozuna59"
    target-branch: "master"
